#!/bin/bash

echo "🌐 Testing HTTPS setup for herbexcellence.store"
echo ""
echo "Please run these commands ON YOUR EC2 SERVER:"
echo ""
echo "1. Connect to EC2:"
echo "   ssh -i herbexint.pem ubuntu@ec2-13-41-78-113.eu-west-2.compute.amazonaws.com"
echo ""
echo "2. Install Certbot:"
echo "   sudo apt update"
echo "   sudo apt install -y certbot"
echo ""
echo "3. Get SSL certificate (when DNS is ready):"
echo "   sudo certbot certonly --standalone -d herbexcellence.store -d www.herbexcellence.store"
echo ""
echo "4. After certificate is obtained, configure Nginx manually with SSL"
echo ""
echo "📝 Make sure ports 80 and 443 are open in EC2 security group!"
