name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    # Deploy Backend
    - name: Deploy Backend
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ubuntu
        SOURCE: "backend/*"
        TARGET: "/var/www/herbexint-api"
        ARGS: "-avz --delete"

    - name: Install Backend Dependencies
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ubuntu
        SCRIPT: "cd /var/www/herbexint-api && npm install"

    - name: Fix Backend Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ubuntu
        SCRIPT: "sudo pkill -f 'node server.js' || true && sleep 2 && cd /var/www/herbexint-api && npm install && nohup node server.js > /var/log/herbexint-backend.log 2>&1 & && sleep 5 && curl -s http://localhost:3001/api/visits || echo 'Backend fix may have failed'"

    # Deploy Frontend
    - name: Deploy Frontend
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ubuntu
        SOURCE: "dist/*"
        TARGET: "/var/www/herbexint"
