name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    # Deploy Backend
    - name: Deploy Backend
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ubuntu
        SOURCE: "backend/*"
        TARGET: "/var/www/herbexint-api"
        ARGS: "-avz --delete"

    - name: Restart Backend
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ubuntu
        PRE_COMMANDS: "cd /var/www/herbexint-api && npm install"
        SCRIPT: "cd /var/www/herbexint-api && pm2 restart herb-backend || pm2 start server.js --name herb-backend && pm2 save"

    # Deploy Frontend
    - name: Deploy Frontend
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ubuntu
        SOURCE: "dist/*"
        TARGET: "/var/www/herbexint"
